### PR TITLE
Converted CSS stylesheets to SCSS

### PR DESCRIPTION
**Pull request by Dmujt**
Changed all css stylesheets to scss, except for the Bootstrap library. Compiled them into one stylesheet with minified css to include on all the pages.

### CODE REVIEW

**Comment by Dmujt** [comment]
Updated to Bootstrap 3, changed classes and elements (functionality is still the same, minor styling changes in the appearance of elements, like buttons and input fields). 

Also added bootstrap3-typeahead library for autocomplete on input fields, since it was dropped from bootstrap 2.

**Comment by berryma4** [comment]
image

There should probably be some emphasis on creating a log entry, since the other actions aren't used much.  Previously, the dropdown was a button itself to create an entry.

**Comment by Dmujt** [comment]
Separated the drop down from the 'New Log Entry' button. 

Also added Qunit for testing, added the initial setup of files with a testing folder in the Olog directory. Added module for testing index.

**Comment by Dmujt** [comment]
Updated the timepicker for the To/From section. It would occasionally appear under the navbar and search bar input, hiding some of the buttons. Also updated the buttons that were not responding on the timepicker (arrows and done button).

**Comment by berryma4** [comment]
image

The text for the entry should not clip words for a new line.
Also, it shouldn't render html (some people have been trying this anyway).  So, the text should be escaped.

Better yet, it would be nice to render markdown, and add a markdown editor to the add entry page.

**Comment by shroffk** [comment]
The last discussion I had with ESS was to add github based markdown support to all Olog clients.

**Comment by Dmujt** [comment]
Added a markdown editor for the textarea when creating new logs/ modifying logs using simplemde-markdown-editor library. Had to change the 'log description' element from a span to a disabled textarea in order to render the markdown on the log index page/ print page. 

The library also comes with a spell check feature, so incorrect words in the textarea are highlighted in red when creating/modifying a log.

**Comment by berryma4** [comment]
Awesome!
Could you add a configuration that makes the whole page "read-only".  ie.  removes add entry/tag/logbook buttons, like when not signed in, but also removes the sign in button.

**Comment by Dmujt** [comment]
Read-only mode is controlled with a button on the navbar.

Added a field to change the eventStart date for logs. After the date is set, it can be viewed in the list of logs (and turned on/off). Right now the eventStart can only be set on the modify-log page.

There was also a 404 error (log not found for id) when trying to set the eventStart date to something past the current date, so I added an error check for this and limited the datepicker to past dates/times.

**Comment by berryma4** [comment]
When editing a log entry, the previous entry text should be pre-loaded.

**Comment by Dmujt** [comment]
Modify log should load the saved text into the textarea now, had to set the markdown editor after the text was loaded for it to show up.

**Comment by Dmujt** [comment]
Added a search bar with tags and a dropdown to add tags of certain types. Clicking/ setting items from the lists on the left will change the tags and search the logs.

The event handlers on the search bar (deleting tags, and typing new ones) still need to be added to the search query.

**Comment by Dmujt** [comment]
Search bar tags can be deleted now (clicked on), and new ones can be typed in. Entering an item from the multilists on the left will automatically highlight/ select it from the list. 

Tags entered by users are checked first, in case an invalid logbook or tag is entered.

If a user types into the search bar without selecting a type from the dropdown, it defaults to the "search" entry type.

Still need to setup default tags to be added to the search url.

**Comment by Dmujt** [comment]
Search with tags is setup. I changed the tag colors for the logbooks/tags/dates to match the search bar.

I also added the event start date to the log information section, and made a few formatting changes for displaying logs.

**Comment by Dmujt** [comment]
I've found a few alternatives to Google analytics to use, but only two that were self-hosting:

https://piwik.org/
http://www.openwebanalytics.com/

These are also open source.

**Comment by berryma4** [comment]
https://piwik.org/

looks better  (at least more active).
It also looks easy to get the data also in elastic.

But, this is gpl, and can't be added to the repo as part of this project.

**Comment by berryma4** [comment]
I guess we will not use a client side analytics, and we will try https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-apache2.html
This way, there is nothing in the repo to force analytics.

**Pull request merged**
